config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, :controllers => {
    :registrations => 'admins/rejistrations',
    :sessions => 'admins/sessions'
  }
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

root 'homes#top'
get 'home/about' => 'homes#about'

get 'customers/my_page' => 'customers#show', as: 'my_page'
get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw'
resource :customers, only: [ :edit, :update]

devise_for :customers

resources :items, only: [ :index, :show]

delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
resources :cart_items, only: [ :index, :update, :destroy, :create]

post 'orders/confirm' => 'orders#confirm'
get 'orders/complete' => 'orders#complete'
resources :orders, only: [ :new, :create, :index,:show]

resources :addresses, only: [ :index, :edit, :create, :update, :destroy]


namespace :admin do
  resources :items, only: [ :index, :new, :create, :show, :edit, :update]
  resources :customers, only: [ :index, :show, :edit, :update]
  resources :genres, only: [ :index, :create, :edit, :update]
  resources :orders, only: [ :index, :show, :update] do
  resources :order_details, only: [ :update]
end
end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

validates :last_name, 
length: { minimum: 1,maximum: 20 }

validates :first_name,
length: { minimum: 1,maximum: 20 }

validates :last_name_kana,
length: { minimum: 1,maximum: 20 }

validates :first_name_kana,
length: { minimum: 1,maximum: 20 }

validates :postal_code, presence: true

validates :address, presence: true

validates :telephone_number,
length: { minimum: 1,maximum: 11 }


  def active_for_authentication?
    super && (is_deleted == false)
  end

  def full_name
    last_name + first_name
  end

  devise :database_authenticatable, :registerable,
  :rememberable, :validatable

  has_many :items
  has_many :cart_items
  has_many :addresses
  has_many :orders
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

def index
  @customers = Customer.page(params[:page])
end

def show
  @customer = Customer.find(params[:id])
end

def edit
@customer = Customer.find(params[:id])
end

def update
@customer = Customer.find(params[:id])
 if @customer.update(customer_params)
   redirect_to admin_customer_path(@customer.id), notice: 'ユーザーの登録情報を変更しました'
 else
   render :edit
 end
end

private

def customer_params
  params.require(:customer).permit(:email,:last_name,:first_name,:last_name_kana,:first_name_kana,:postal_code,:address,:telephone_number,:is_deleted)
end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  protected
  
  def reject_user
    @customer = Customer.find(email: params[:customer][:email])
    if @customer
      if @customer.valid_password?(params[:customer][:password]) && (@customer.is_deleted == true )
         flash[:notice] = "退会済みです。再度ご登録をしてご利用ください。"
          redirect_to new_customer_registration_path
        else
           flash[:notice] = "項目を入力してください"
         end
    end
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_customer!

  def show
    @customer = current_customer
  end

  def edit
    @customer = current_customer
  end

  def update
    @customer = current_customer
    if @customer.update(params_customer)
      redirect_to my_page_path, notice: '登録情報を変更しました'
    else
       render :edit
    end
  end

  def withdraw
    @customer = current_customer
    # is_deletedカラムをtrueに変更することにより削除フラグを立てる
    @customer.update(is_deleted: true)
    reset_session
    flash[:notice] = "退会処理を実行いたしました"
    redirect_to root_path
  end

  def unsubscribe
    @customer =current_customer
  end

  private

  def params_customer
    params.require(:customer).permit(:last_name,:first_name,:last_name_kana,:first_name_kana,:postal_code,:address,:telephone_number,:email)
  end


end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/edit.html.erb
<div class="container">

   <h4>会員情報編集</h4>

   <% if @customer.errors.any? %>
    <div id="error_explanation">
     <h2><%= @customer.errors.count %>件のエラーが発生しました</h2>
      <ul>
       <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %>
       <% end %>
        </li>
      </ul>
    </div>
   <% end %>

  <div class="row">
   <div class="col-lg-8">
    <%= form_with model:@customer,url:customers_path, local:true do |f| %>
     <table>
      <tr>
       <th>氏名</th>
       <td><%= f.text_field :last_name %> <%= f.text_field :first_name %></td>
      </tr>

      <tr>
       <th>フリガナ</th>
       <td><%= f.text_field :last_name_kana %> <%= f.text_field :first_name_kana %></td>
      </tr>

      <tr>
       <th>郵便番号</th>
       <td><%= f.text_field :postal_code %></td>
      </tr>

      <tr>
       <th>住所</th>
       <td><%= f.text_field :address %></td>
      </tr>

      <tr>
       <th>電話番号</th>
       <td><%= f.text_field :telephone_number %></td>
      </tr>

      <tr>
       <th>メールアドレス</th>
       <td><%= f.text_field :email %></td>
      </tr>
      
      <tr>
       <th></th>
       <td><%= f.submit "編集内容を保存",class:"btn btn-success" %>　　　　　<%= link_to "退会する",unsubscribe_path,class:"btn btn-sm btn-danger" %></td>
      </tr>
      
     </table>
    <% end %>
   </div>
  </div>
</div>

app/views/customers/show.html.erb
<div class="container">

  <span class=”title”><h4>マイページ</h4></span>
  <h4><strong>登録情報</strong>　<%= link_to "編集する",edit_customers_path,class:"btn btn-success" %></h4>

 <div class="row">
   <div class="col-7">
    <table class="table table-bordered">
     <tr>
      <th class="table-secondary" style="width: 25%">氏名</th>
      <td><%= @customer.last_name %> <%= @customer.first_name %></td>
     </tr>

     <tr>
       <th class="table-secondary">カナ</th>
       <td><%= @customer.last_name_kana %> <%= @customer.first_name_kana %></td>
     </tr>

     <tr>
       <th class="table-secondary">郵便番号</th>
       <td><%= @customer.postal_code %></td>
     </tr>

     <tr>
       <th class="table-secondary">住所</th>
       <td><%= @customer.address %></td>
     </tr>

     <tr>
       <th class="table-secondary">電話番号</th>
       <td><%= @customer.telephone_number %></td>
     </tr>

     <tr>
       <th class="table-secondary">メールアドレス</th>
       <td><%= @customer.email %></td>
     </tr>
    </table>
    <div clas="col-5">
    </div>
   </div>
  </div>

<p><strong>配送先</strong>   　　<%= link_to "一覧を見る",addresses_path,class:"btn btn-sm btn-primary" %></p>
<p><strong>注文履歴</strong>  　<%= link_to "一覧を見る",orders_path,class:"btn btn-sm btn-primary" %></p>



</div>

app/views/customers/unsubscribe.html.erb
<p class="unsubscribe">
   <strong>本当に退会しますか?</strong><br>
   退会すると、会員登録情報や<br>
   これまでの購入履歴が閲覧できなくまります。<br>
   退会する場合は、「退会する」をクリックしてください。</p>
  
  <div class="unsubscribe-button">
   <%= link_to "退会しない", my_page_path(current_customer.id),class:"btn btn-sm btn-primary" %>
   <%= link_to "退会する", withdraw_path, method: :patch, data: {confirm: "本当に退会しますか？"},class:"btn btn-sm btn-danger" %>
  </div> 