config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, :controllers => {
    :registrations => 'admins/rejistrations',
    :sessions => 'admins/sessions'
  }
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

root 'homes#top'
get 'home/about' => 'homes#about'

get 'customers/my_page' => 'customers#show', as: 'my_page'
get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw'
resource :customers, only: [ :edit, :update]

devise_for :customers

resources :items, only: [ :index, :show]

delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
resources :cart_items, only: [ :index, :update, :destroy, :create]

post 'orders/confirm' => 'orders#confirm'
get 'orders/complete' => 'orders#complete'
resources :orders, only: [ :new, :create, :index,:show]

resources :addresses, only: [ :index, :edit, :create, :update, :destroy]


namespace :admin do
  resources :items, only: [ :index, :new, :create, :show, :edit, :update]
  resources :customers, only: [ :index, :show, :edit, :update]
  resources :genres, only: [ :index, :create, :edit, :update]
  resources :orders, only: [ :index, :show, :update] do
  resources :order_details, only: [ :update]
end
end

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  def subtotal
    item.with_tax_price * amount
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :authenticate_customer!
  def index
   @cart_items = current_customer.cart_items 
   @total = 0
   @cart_items.each do |cart_item| 
   tal = cart_item.subtotal
   @total += tal
  end
  end
  
  def update
    @cart_item = CartItem.find(params[:id])
    @cart_item.update(cart_item_params)
    redirect_to cart_items_path
  end
  
  def destroy
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
    redirect_to cart_items_path
  end
  
  def create
    @cart_item = CartItem.new(cart_item_params)
    @cart_item.customer_id = current_customer.id
    #追加した商品がカート内に存在した場合
  if cart_item = current_customer.cart_items.find_by(item_id: params[:cart_item][:item_id])
     cart_item.amount += params[:cart_item][:amount].to_i
     cart_item.save
     redirect_to cart_items_path
     #追加した商品がカート内に存在しなかった
  else @cart_item.save
      redirect_to cart_items_path
  end
  end
  
  def destroy_all
    current_customer.cart_items.destroy_all
    redirect_to cart_items_path
  end

  def cart_item_params
    params.require(:cart_item).permit(:item_id,:amount)
  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/views/cart_items/index.html.erb
<div class= "container">
 <div class="row">
  <h4>ショッピングカート</h4>
  
  <% if @cart_items.present? %>
  
  <div class=" col-lg-12">
   <div class="parent">
   　<div class="button"><%= link_to "カートを空にする",cart_items_destroy_all_path, method: :delete, data: {confirm: "本当にカートを空にしますか？"},class:"btn btn-sm btn-danger" %></div>
 　</div>
  </div>

  <div class="col-lg-12">
   <table class="table table-bordered">
    <tr>
     <th>商品名</th>
     <th>単価（税込）</th>
     <th>数量</th>
     <th>小計</th>
     <th></th>
    </tr>

     <% @cart_items.each do |cart_item| %>
     <tr>

     <td>
     <%= attachment_image_tag cart_item.item, :image, :fill, 100, 100, format: 'jpeg' %>
     <%= cart_item.item.name %>
     </td>

     <td>
      <%= cart_item.item.with_tax_price.to_s(:delimited, delimiter: ',') %>
     </td>

      <%= form_with model:cart_item, local:true do |f| %>

     <td>
      <span class="button"><%= f.select :amount, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] %>  <%= f.submit "変更",class:"btn btn-success" %></span>
     </td>

     <td>
      <%= cart_item.subtotal.to_s(:delimited, delimiter: ',') %>
     </td>

     <td>
      <span class="button"><%= link_to "削除する",cart_item_path(cart_item.id), method: :delete, data: {confirm: "本当に削除しますか？"},class:"btn btn-sm btn-danger" %></span>
     </td>

     <% end %>
     <% end %>
     </tr>
   </table>
  </div>

  <div class="col-lg-12">
   <div class= "col-lg-7">
    <span class="button"><%= link_to "買い物を続ける", root_path, class:"btn btn-sm btn-primary" %></span>
   </div>

   <div class="col-lg-4">
    <table class="table table-bordered table-sm" >
      <tr>
      <th style="width: 20%">合計金額</th>
      <td style="width:25%">¥<%= @total.to_s(:delimited, delimiter: ',') %></td>
      </tr>
    </table>
   </div>
  </div>

   <div class="col-lg-12">
    <div class="parent2">
   <span class="button"><%= link_to "情報入力に進む",new_order_path,class:"btn btn-success" %></span>
   </div>
   </div>
 </div>
</div>


<% else %>

<div class="enpty">
 <span class="enpty-word"><strong>現在カート内に商品はありません</strong></spna>
</div>

<% end %>