config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, :controllers => {
    :registrations => 'admins/rejistrations',
    :sessions => 'admins/sessions'
  }
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

root 'homes#top'
get 'home/about' => 'homes#about'

get 'customers/my_page' => 'customers#show', as: 'my_page'
get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw'
resource :customers, only: [ :edit, :update]

devise_for :customers

resources :items, only: [ :index, :show]

delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
resources :cart_items, only: [ :index, :update, :destroy, :create]

post 'orders/confirm' => 'orders#confirm'
get 'orders/complete' => 'orders#complete'
resources :orders, only: [ :new, :create, :index,:show]

resources :addresses, only: [ :index, :edit, :create, :update, :destroy]


namespace :admin do
  resources :items, only: [ :index, :new, :create, :show, :edit, :update]
  resources :customers, only: [ :index, :show, :edit, :update]
  resources :genres, only: [ :index, :create, :edit, :update]
  resources :orders, only: [ :index, :show, :update] do
  resources :order_details, only: [ :update]
end
end

end

app/models/address.rb
class Address < ApplicationRecord
  
  
validates :name, 
 length: { minimum: 1 }

validates :postal_code, presence: true

validates :address, presence: true

  
  belongs_to :customer
  
def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

validates :last_name, 
length: { minimum: 1,maximum: 20 }

validates :first_name,
length: { minimum: 1,maximum: 20 }

validates :last_name_kana,
length: { minimum: 1,maximum: 20 }

validates :first_name_kana,
length: { minimum: 1,maximum: 20 }

validates :postal_code, presence: true

validates :address, presence: true

validates :telephone_number,
length: { minimum: 1,maximum: 11 }


  def active_for_authentication?
    super && (is_deleted == false)
  end

  def full_name
    last_name + first_name
  end

  devise :database_authenticatable, :registerable,
  :rememberable, :validatable

  has_many :items
  has_many :cart_items
  has_many :addresses
  has_many :orders
end

app/models/genre.rb
class Genre < ApplicationRecord
  
  validates :name,
  length: { minimum: 1, maximum: 15 }
  
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  
  validates :name,
  length: { minimum: 1, maximum: 20 }
  
  validates :introduction,
  length: { minimum: 1, maximum: 50 }
  
  validates :price, presence: true
  
  validates :is_active, inclusion: { in: [true, false] }

  attachment :image

  has_many :cart_items
  has_many :order_detail
  belongs_to :genre

  def with_tax_price
  (price * 1.1 ).floor
  end

end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: { credit_card: 0, transfer: 1 }
  belongs_to :customer
  has_many :order_details
  #入金待ち:0、入金確認:1、製作中:2、発送準備:３、発送済:４
  enum status: { waiting: 0,
                 paid_up: 1,
                 producting: 2,
                 shipping: 3,
                 shipped: 4 }
  
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  
  enum making_status: { impossible: 0,
                 waiting: 1,
                 producting: 2,
                 complete: 3 }
  
  
  def with_tax_price
  (price * 1.1 ).floor
  end
  
  def subtotal
    with_tax_price * amount 
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
def top
  @genres = Genre.all
  @items = Item.limit(4).order(" created_at DESC ")
end

def about
end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

def index
@items = Item.page(params[:page])
@genres = Genre.all
end

def show
  @item = Item.find(params[:id])
  @genres = Genre.all
  @cart_item = CartItem.new
end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_customer!
  def new
    @order = Order.new
  end

  def confirm
    @cart_items = current_customer.cart_items
    @total = 0
    @cart_items.each do |cart_item|
    tal = cart_item.subtotal
    @total += tal
    end


    @order = Order.new(order_params)
    #hidden_fieldで注文機能へ情報を送るためshipping_costとtotal_paymentの金額を定義
    @order.shipping_cost = 800
    @order.total_payment = @total + 800

    #newアクションで選択したお届け先によって条件分岐
    if params[:order][:select_address] == "0"
      @order.postal_code = current_customer.postal_code
      @order.address = current_customer.address
      @order.name = current_customer.first_name + current_customer.last_name
    elsif params[:order][:select_address] == "1"
      @address = Address.find(params[:order][:address_id])
      @order.postal_code = @address.postal_code
      @order.address = @address.address
      @order.name = @address.name
    elsif params[:order][:select_address] == "2"
      @order.postal_code = params[:order][:postal_code]
      @order.address = params[:order][:address]
      @order.name = params[:order][:name]
    end

  end

  def create

    order = Order.new(order_params) #確認画面から送られてきた情報を取得
    order.customer_id = current_customer.id
    order.status = 0
    order.save
    cart_items = current_customer.cart_items #42,43でカート内商品の情報をすべて取得し1つずつ格納
    cart_items.each do |cart_item|
      order_detail = OrderDetail.new
      order_detail.order_id = order.id
      order_detail.item_id = cart_item.item.id
      order_detail.price = cart_item.item.price
      order_detail.amount = cart_item.amount
      order_detail.making_status = 0
      order_detail.save
    end
    current_customer.cart_items.destroy_all #カート内商品を全て削除
    redirect_to orders_complete_path
  end

  def index
    @orders = current_customer.orders
  end


  def show
    @order = Order.find(params[:id])
    @total = 0
    @order.order_details.each do |order_detail| 
    tal = order_detail.subtotal
    @total += tal
  end
  end


  private
  def order_params
    params.require(:order).permit(:payment_method,:postal_code, :address, :name,:total_payment,:shipping_cost)
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/order_details_helper.rb
module OrderDetailsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>

        <nav class="navbar navbar-expand-lg navbar-dark bg-secondary">
            <div class="container">
            <a class="navbar-brand" href="/">nagano_cake</a>
            <% if current_customer %>
             <div>ようこそ、<%= current_customer.full_name %>さん！</div>
            <% end %>

          <ul class= "navbar-nav ml-auto">

           <% if customer_signed_in? %>

            <li class="nav-item">
             <%= link_to "マイページ",my_page_path(current_customer),class:"nav-link text-light" %>
            </li>

            <li class="nav-item">
             <%= link_to "商品一覧",items_path,class:"nav-link text-light" %>
            </li>

            <li class="nav-item">
             <%= link_to "カート",cart_items_path,class:"nav-link text-light" %>
            </li>

            <li class="nav-item">
             <%= link_to "ログアウト", destroy_customer_session_path, method: :delete,class:"nav-link text-light" %>
            </li>

          <% elsif admin_signed_in? %>

            <li class="nav-item ">
             <%= link_to "商品一覧", admin_items_path,class:"nav-link text-light" %>
            </li>

            <li class="nav-item">
             <%= link_to "会員一覧", admin_customers_path,class:"nav-link text-light" %>
            </li>

            <li class="nav-item">
             <%= link_to "注文履歴一覧", admin_orders_path,class:"nav-link text-light" %>
            </li>

            <li class="nav-item">
             <%= link_to "ジャンル一覧", admin_genres_path,class:"nav-link text-light" %>
            </li>

            <li class="nav-item">
             <%= link_to "ログアウト", destroy_admin_session_path, method: :delete,class:"nav-link text-light" %>
            </li>


          <% else %>

            <li class="nav-item">
             <%= link_to "about",home_about_path,class:"nav-link text-light" %>
            </li>

            <li class="nav-item">
             <%= link_to "商品一覧",items_path,class:"nav-link text-light" %>
            </li>

            <li class="nav-item">
             <%= link_to "新規登録",new_customer_registration_path,class:"nav-link text-light" %>
            </li>

            <li class="nav-item">
              <%= link_to"ログイン",customer_session_path,class:"nav-link text-light" %>
            </li>

          <% end %>
         </ul>
        </nav>
      </div>
    </header>
   <main>
    <% flash.each do |key, value| %>
     <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

    <%= yield %>
   </main>

    <footer>
     <div class="mt-5 bg-secondary text-white">
        <div class= "row">
         <div class="mx-auto">
          <p>CopyRight Infratop.inc</p>
         </div>
        </div>
      </div>
    </footer>
  </body>
</html>